### PR TITLE
labels: Increase specificity of label selector

### PR DESCRIPTION
**Pull request by codemacabre**
Fixes https://github.com/openownership/visualisation-tool/issues/134

### CODE REVIEW

**Review by radix0000 — CHANGES_REQUESTED** [review]
Sorry for slow reply. Shouldn't this be:

`d3.selectAll('.edgeLabels .edgeLabel .label').each(function (d, i) {`

with spaces rather than commas in the selector (to select a label within an edgeLabel within an edgeLabels, we are trying narrow the selection right?), or am I missing something? It looks like with the commas in there it is going to widen it to all label, edgeLabel and edgeLabels elements?

**Comment by codemacabre** [comment]
@radix0000 Whoops, misread a couple of things there. Please see the update which should sort things out.

**Review by radix0000 — APPROVED** [review]
Thanks, approved.

**Comment by andrewShillito** [comment]
Looks good to me also. Thank you all for making this change.

**Pull request merged**
