### PR TITLE
Handle unspecified interested parties (hanging edges)

### LINKED ISSUE #157: Handling unspecified interested parties (hanging edges) in BODS data
In BODS 0.4, relationships (edges) are specified as existing between a `subject` (usually represented by a recordId (string value)) and an `interestedParty` (usually represented by a recordId(string value)).

However, sometimes an interested party (or a subject) might not be provided in the data, in which case the value for the `interestedParty` is an [unspecified record object](https://standard.openownership.org/en/latest/standard/reference.html#unspecifiedrecord).

This is the case in [this example file](https://github.com/openownership/data-standard/blob/main/examples/listed-company-exempt-from-disclosure.json):

```
[...]
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "4c7ea3bfbe6c",
      "interestedParty": {
        "reason": "subjectExemptFromDisclosure",
        "description": "Exempt from disclosure as a company listed on a recognised stock exchange"
      }
    }
[...]
```
An error like this is currently generated when submitting that example file:

```
Uncaught runtime errors:
ERROR
n is undefined
./node_modules/dagre-d3/lib/render.js/e.exports/m/<@http://localhost:9000/main.js:2:574459
./node_modules/dagre-d3/lib/render.js/e.exports/m/<@http://localhost:9000/main.js:2:574402
m@http://localhost:9000/main.js:2:575087
./src/index.js/c<@http://localhost:9000/main.js:2:57176
p@http://localhost:9000/main.js:2:53749
./demo/index.js/e/<@http://localhost:9000/main.js:2:53572
c@http://localhost:9000/main.js:2:773535
./node_modules/regenerator-runtime/runtime.js/u/i._invoke@http://localhost:9000/main.js:2:773289
./node_modules/regenerator-runtime/runtime.js/_/</<@http://localhost:9000/main.js:2:773894
t@http://localhost:9000/main.js:2:524
a@http://localhost:9000/main.js:2:736
```

#### Suggested handling

If a relationship statement's `interestedParty` or `subject` value is an object (not a string):

- create a special 'Unspecified' node which renders like so (question mark in a stack of dotted circles), plus a label of 'Unspecified':

image
- render the edge as normal.

### PR DESCRIPTION
**Pull request by codemacabre**
Closes #157

### CODE REVIEW

**Review by radix0000 — APPROVED** [review]
Looks good. Probably outside scope, but notice that it displays nothing if there is only a relationship in the data: https://github.com/openownership/data-standard/blob/main/tests/data/valid-statements/relationship.json Potentially could display relationship with undefined entities at either end.

**Comment by kd-ods** [comment]
> Potentially could display relationship with undefined entities at either end.

@codemacabre - according to the new draft spec, we should do as @radix0000 suggests. In the spec:

"Unknown node drawn and connected as interested party" because "interestedParty is not a recordId string matching a connectable node"

and

"Unknown node drawn and connected as subject" because "subject is not a recordId string matching a connectable node"

**Comment by codemacabre** [comment]
This does draw unknown nodes (stacked with a question mark icon) if the relationship lists `subject` and/or `interestedParty` as unspecified. But not if they are specific recordIds (albeit not defined as nodes in the data). I'll fix that.

**Comment by codemacabre** [comment]
This is now fixed. The single relationship @radix0000 posted above now renders as:
image

**Pull request merged**
