### PR TITLE
Interest types mapping

### LINKED ISSUE #97: Interest types - owns/controls mapping missing
At least five interest types don’t seem to have a colour mapping to “owns” or “controls”:
other-influence-or-control
appointment-of-board
senior-managing-official
rights-to-surplus-assets-on-dissolution
settlor-of-trust

This is regardless of interest level being direct or indirect.

Data: https://drive.google.com/file/d/1LxkG2qt4icpO7tJ3luvYgo5czGKbLN09/view
bods(4)

### PR DESCRIPTION
**Pull request by codemacabre**
This PR closes #97 with the following changes:
- Add support for interests categories rather than just interests types
- Add support for missing interests
- Add text labels even when no share %, either 'Owns' or 'Controls'
- Fix unknown interests dashed lines & improve support for unknown interests
- Fix edge stroke widths based on share %

### CODE REVIEW

**Comment by radix0000** [comment]
For this example (https://github.com/openownership/data-standard/blob/main/examples/bods-package-annotations.json) I am getting the following error:

```
Uncaught runtime errors:
ERROR
e is undefined
./src/model/edges/edges.js/v/o</C<@http://localhost:9000/main.js:2:19671
./src/model/edges/edges.js/v/o<@http://localhost:9000/main.js:2:19859
v@http://localhost:9000/main.js:2:18938
_@http://localhost:9000/main.js:2:21074
./src/index.js/a<@http://localhost:9000/main.js:2:15492
h@http://localhost:9000/main.js:2:10686
./demo/index.js/e/<@http://localhost:9000/main.js:2:10509
c@http://localhost:9000/main.js:2:719599
./node_modules/regenerator-runtime/runtime.js/a/s._invoke@http://localhost:9000/main.js:2:719353
./node_modules/regenerator-runtime/runtime.js/_/</<@http://localhost:9000/main.js:2:719958
t@http://localhost:9000/main.js:2:524
u@http://localhost:9000/main.js:2:736
```

There are two entities and a relationship connecting them, so doesn't appear related to missing statements.

**Comment by codemacabre** [comment]
Thanks @radix0000, the example file didn't have any interests listed which wasn't handled. It should now produce a dashed line as per the [spec](https://docs.google.com/document/d/1hCjhl7PLQ3bOpeeqO9gis9lDcNbV_HKIpBwPNklK6Cs/).

Question for @kd-ods: the spec seems to imply no unknown text nodes are ever rendered. Is this correct? The current behaviour is that unknown text is _always_ rendered, except when the interestType is not `shareholding` or `votingRights`, so wanted to check before stripping that code out entirely.

**Comment by kd-ods** [comment]
> the spec seems to imply no unknown text nodes are ever rendered. Is this correct?

Do you mean by 'unknown text nodes': 'unknown' text labels for edges? If so, yes, that is the implication. For the record (and for you to sense-check!), my rationale is:

- 'unknown' is unhelpful in that it could mean any number of things:
  1. 'we don't know if there is a relationship here or not'
  2. 'unknown type of interest'
  3. 'unknown magnitude of interest'
  4. 'unknown directness - are there intermediaries here'
- the risk is that in interpreting the visualisation, the viewer picks only one of those meanings, when - actually - all of (ii) - (iv) apply, and (i) does not apply.
- the risk exists whether or not the 'unknown' label is there, but I think the label prompts the viewer to read more specificity or meaning into interpretation of the edge visual.
- in any case, we now have the wonderful attribute-viewing facility, so that people can select the edge and see for themselves what is and isn't known.

Maybe I'm off the mark, though.

**Review by radix0000 — APPROVED** [review]
Looks fine.

**Pull request merged**
