### PR TITLE
Handle BODS 0.4 data

### LINKED ISSUE #151: Update visualiser to handle BODS 0.4 data
BODS 0.4 has now been released ([branch](https://github.com/openownership/data-standard/tree/0.4.0) | [docs](https://standard.openownership.org/en/0.4.0/) | [changelog](https://standard.openownership.org/en/0.4.0/standard/changelog.html)).

The visualiser now needs to be able to parse and render BODS 0.4 data. (While retaining the ability to parse and render BODS 0.2, and BODS 0.3 data).

Test and example data can be found in the repo. See the [Example Data docs page](https://standard.openownership.org/en/0.4.0/examples/index.html) for some context for some example data.

### PR DESCRIPTION
**Pull request by codemacabre**
Add multiple conditionals to check version number & adjust property names accordingly. Tests for 0.4 data while maintaining compatibility with earlier versions.

Closes #151

### CODE REVIEW

**Comment by codemacabre** [comment]
I've done considerable testing of the 0.34 and 0.4 [example data](https://standard.openownership.org/en/0.4.0/examples/index.html) but due to my inexperience with the data standard, it might be better for others (@radix0000 perhaps) to review that this is outputting expected visualisations.

Here is the 0.4 example data for [Fermcat](https://github.com/openownership/data-standard/blob/0.4.0/examples/fermcat.json), for example:
bods which at a cursory glance looks to render without issues, but on inspection the ownership adds up to 200% - is this expected?

**Comment by codemacabre** [comment]
Similarly with [Tecido](https://github.com/openownership/data-standard/blob/0.4.0/examples/tecido.json), which adds up to 110%:
bods2

**Comment by codemacabre** [comment]
I think I solved it by checking for 'closed' records and cross-checking closed relationships' `interestedParty` ids. The output for changes over time are now as follows:


bods
bods2

**Comment by kathryn-ods** [comment]
Those images are definitely correct now, good work @codemacabre :) 

I'll leave it to @rhiaro or @radix0000 to review the code itself

**Comment by kd-ods** [comment]
Just to clarify (for the record), the Tecido and Fermcat example BODS files show how a set of BODS statements can represent changing beneficial ownership over time.

> I think I solved it by checking for 'closed' records and cross-checking closed relationships' interestedParty ids. 

Your solution (for the problem of out-of-date information being represented alongside current information) means that only the latest set of information in the dataset is visualised. (Which is fine!)

There is a separate issue (#141) in the second sprint which will enable a more refined handling of datasets with a time dimension.

**Review by radix0000 — APPROVED** [review]
Looks good. Have approved but one thing you might want to think about is what I am doing with data review tool, where you have a `version_greater_or_equal_to` function, so might all just work for 0.5 etc. (imagining massive restructuring of 0.4 won't be happening every version), rather than doing:

```
 if (version === '0.4') {
```
Also an observation (more to think about as a potential future feature) is that annotations are something that might be useful for the visualiser to show, e.g. `bods-package-linking-annotations.json`

**Comment by codemacabre** [comment]
Thanks @radix0000 I've changed the version checks to include versions >= 0.4.

I believe annotations are on the list of things to do, perhaps as an enhancement after https://github.com/openownership/visualisation-tool/issues/55 has been completed.

**Review by radix0000 — APPROVED** [review]
Looks good.

**Pull request merged**
